apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-and-clean
spec:
  params:
    - name: uid
      description: uid
  workspaces:
    - name: task-pvc
      mountPath: /workspace/source 
  steps:
    - name: git-clone
      command: ["/bin/sh", "-c"]
      args:
        - | 
          set -e -o

          cd /workspace/source/$(params.uid) ;
          mkdir build-folder ;
          cp target/*.jar build-folder/ ;

          env | grep KUBERNETES
          TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`    
          oc login --insecure-skip-tls-verify --token=$TOKEN --server=https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT ;

          oc new-build  --name hello-world --strategy=source --binary=true -n tekton-springboot-deploy --image-stream=ubi8-openjdk-11 || true ;

          oc start-build hello-world --from-dir=build-folder/. -n tekton-springboot-deploy --follow --wait ;

          oc new-app hello-world -n tekton-springboot-deploy || true ;

          oc expose svc/hello-world -n tekton-springboot-deploy || true ;

          cd / ;
          rm -Rf /workspace/source/$(params.uid) ;
      image: image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven
